# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7b048cb8986102a31b5601b4f30638625d7bdc79063fc40783f019bc49f439945182eb62125cde04b807d55e1e363ee5e30710788257261c1411f1cbd82f2f69

test:
  secret_key_base: 43e834be1af2ec507bfd6c2f4c1c30d2040055f54ea09bd2931e68d134ee558991bc0347c16c9fb194dc989b5c089c6a9ec2118f6854cd4679a7c92cdd0b6e99

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
